/** @babel */

export const ACTIONS = {
  OPEN_INPUT_BOTTOM_VIEW: 'OPEN_INPUT_BOTTOM_VIEW',
  CLOSE_INPUT_BOTTOM_VIEW: 'CLOSE_INPUT_BOTTOM_VIEW',
  OPEN_RESULTS_MODAL: 'OPEN_RESULTS_MODAL',
  JQ_FILTER_REQUEST: 'JQ_FILTER_REQUEST',
  SET_ACTIVE_PANE: 'SET_ACTIVE_PANE',
  FOCUS_BOTTOM_INPUT: 'FOCUS_BOTTOM_INPUT'
}
