/** @babel */

export const ACTIONS = {
  OPEN_PANEL_VIEW: 'OPEN_PANEL_VIEW',
  CLOSE_PANEL_VIEW: 'CLOSE_PANEL_VIEW',
  JQ_FILTER_REQUEST: 'JQ_FILTER_REQUEST',
  SET_ACTIVE_PANE: 'SET_ACTIVE_PANE',
  OPEN_MODAL_VIEW: 'OPEN_MODAL_VIEW',
  FOCUS_BOTTOM_INPUT: 'FOCUS_BOTTOM_INPUT'
}
