/** @babel */

export const ACTIONS = {
  TOGGLE_PANEL_VIEW: 'TOGGLE_PANEL_VIEW',
  JQ_FILTER_SUCCESS: 'JQ_FILTER_SUCCESS',
  JQ_FILTER_REQUEST: 'JQ_FILTER_REQUEST',
  JQ_FILTER_FAILURE: 'JQ_FILTER_FAILURE',
  SET_ACTIVE_PANE: 'SET_ACTIVE_PANE',
  OPEN_MODAL_VIEW: 'OPEN_MODAL_VIEW'
}
