/** @babel */

export const ACTIONS = {
  TOGGLE_PANEL_VIEW: 'TOGGLE_PANEL_VIEW',
  JQ_FILTER_REQUEST: 'JQ_FILTER_REQUEST',
  SET_ACTIVE_PANE: 'SET_ACTIVE_PANE',
  OPEN_MODAL_VIEW: 'OPEN_MODAL_VIEW',
  SHOW_ERROR_MESSAGE: 'SHOW_ERROR_MESSAGE'
}
